[Migration] Asset conversion tutorial from Polkadot Wiki
papermoonio/polkadot-ecosystem-docs-draft pull request #39
Opened 2024-08-29 00:43 UTC by nhussein11

This pull request involves migrating the Asset Conversion tutorial from the Polkadot Wiki to our documentation. The tutorial covers creating liquidity pools, adding liquidity, and performing token swaps using the Asset Conversion pallet. 

Polkadot wiki link: https://wiki.polkadot.network/docs/learn-guides-asset-conversion 

Please note that there may be redundant and similar sections on the Polkadot wiki. Therefore, I suggest splitting this page into the following:

- asset-conversion-introduction.md
- creating-a-liquidity-pool.md
- adding-liquidity-to-a-pool.md
- swapping-assets.md
- withdrawing-assets.md

2024-08-29 18:39 UTC, 0xLucca commented on docs/build-on-polkadot/parachains/asset-hub/image-1.png
What are these images?

2024-08-29 18:40 UTC, 0xLucca commented on docs/build-on-polkadot/parachains/asset-hub/asset-conversion.md
> +- Access the [Polkadot.Js App](https://polkadot.js.org/apps){target=\_blank} interface and connect it to the intended blockchain
```suggestion
- Access the [Polkadot.ss Apps](https://polkadot.js.org/apps){target=\_blank} interface and connect it to the intended blockchain
```

2024-08-29 18:57 UTC, 0xLucca commented on docs/build-on-polkadot/parachains/asset-hub/asset-conversion.md
> +      1. Select the **AssetConversion** pallet
```suggestion
2. Choose the **assetConversion** pallet and click on the **add_liquidity** extrinsic
      1. Select the **assetConversion** pallet
```

2024-08-29 19:01 UTC, 0xLucca commented on docs/build-on-polkadot/parachains/asset-hub/asset-conversion.md
> +As the above image shows, the **lp_token** ID created for this pool is 19. This ID is essential to identify the liquidity pool and the LP tokens associated with it.
```suggestion
As the above image shows, the **lpToken** ID created for this pool is 19. This ID is essential to identify the liquidity pool and the LP tokens associated with it.
```

2024-08-29 19:17 UTC, 0xLucca commented on docs/build-on-polkadot/parachains/asset-hub/asset-conversion.md
> +### Swapping From an Exact Amount of Tokens
The two images have different extrinsics:
one has **swapTokensForExactTokens** and the other has **swapExactTokensForTokens**

2024-08-29 19:19 UTC, 0xLucca commented on docs/build-on-polkadot/parachains/asset-hub/asset-conversion.md
> +      2. Choose the **swapForExactTokens** extrinsic from the list of available extrinsics
```suggestion
      2. Choose the **swapExactTokensForTokens** extrinsic from the list of available extrinsics
```

2024-08-29 19:20 UTC, 0xLucca commented on docs/build-on-polkadot/parachains/asset-hub/asset-conversion.md
> +        ![Swap For Exact Tokens Extrinsic](/polkadot-ecosystem-docs-draft/images/building-on-polkadot/parachains/asset-hub/asset-conversion/asset-conversion-8.webp)
```suggestion
        ![Swap From Exact Tokens Extrinsic](/polkadot-ecosystem-docs-draft/images/building-on-polkadot/parachains/asset-hub/asset-conversion/asset-conversion-8.webp)
```

2024-08-29 19:20 UTC, 0xLucca commented on docs/build-on-polkadot/parachains/asset-hub/asset-conversion.md
> +![Swap For Exact Tokens Event](/polkadot-ecosystem-docs-draft/images/building-on-polkadot/parachains/asset-hub/asset-conversion/asset-conversion-10.webp)
```suggestion
![Swap From Exact Tokens Event](/polkadot-ecosystem-docs-draft/images/building-on-polkadot/parachains/asset-hub/asset-conversion/asset-conversion-10.webp)
```

2024-08-29 19:47 UTC, nhussein11 commented on docs/build-on-polkadot/parachains/asset-hub/image-1.png
seems that they got leaked from our snagit template hahah 🙃

2024-09-05 19:10 UTC, dawnkelly09 requested changes
Formatting and grammar suggestions. Thank you!

2024-09-05 19:10 UTC, dawnkelly09 commented on docs/build-on-polkadot/parachains/asset-hub/register-a-foreign-asset.md
>  3. Select the Foreing Assets pallet
```suggestion
3. Select the Foreign Assets pallet
```

2024-09-05 19:10 UTC, dawnkelly09 commented on docs/build-on-polkadot/parachains/asset-hub/register-a-foreign-asset.md
>        3. Select the **foreignAssets** pallet from the dropdown list
```suggestion
      3. Select the **`foreignAssets`** pallet from the dropdown list
```

2024-09-05 19:10 UTC, dawnkelly09 commented on docs/build-on-polkadot/parachains/asset-hub/register-a-foreign-asset.md
>        4. Choose the **create** extrinsic
```suggestion
      4. Choose the **`create`** extrinsic
```

2024-09-05 19:10 UTC, dawnkelly09 commented on docs/build-on-polkadot/parachains/asset-hub/register-a-foreign-asset.md
>      - **minBalance** - the minimum balance required to hold this asset
```suggestion
    - **`minBalance`** - the minimum balance required to hold this asset
```

2024-09-05 19:11 UTC, dawnkelly09 requested changes
Formatting and grammar suggestions. Thank you!

2024-09-15 05:29 UTC, albertov19 commented
@nhussein11 what is the status of this PR? Dawn left some comments as well as Vale.

Should we review this one? Or you ported this changes to the new repo?

2024-09-23 10:53 UTC, nhussein11 commented
> @nhussein11 what is the status of this PR? Dawn left some comments as well as Vale.
> 
> Should we review this one? Or you ported this changes to the new repo?

@albertov19, I have addressed all of Dawn's comments. As for Vale's comments, the remaining ones are false positives. I think this PR is ready to be merged. After that, it should be ported to the new repository since this content is not there yet.

2024-09-23 12:35 UTC, merged